Issue (#38): a11y improvements
vaadin/vaadin-details pull request #41
Opened 2021-02-08 13:17 UTC by niiyeboah

- Add `aria-controls` attr to toggle button
- Change content part to `section` element
- Add `_getContentId` method to create unique content ids
- Add `id` attr to content part

2021-02-08 16:51 UTC, web-padawan requested changes

2021-02-08 16:51 UTC, web-padawan commented on src/vaadin-details.js
> +    this._contentId = this._getContentId();
Please align this with the implementation of [`vaadin-radio-group`](https://github.com/vaadin/vaadin-radio-button/blob/ac80d5e6cac1b266c44da81bac79a1c13e930d15/src/vaadin-radio-group.js#L263-L264):

```js
    const uniqueId = (DetailsElement._uniqueId = 1 + DetailsElement._uniqueId || 0);
    this. _contentId = `${this.constructor.is}-content-${uniqueId}`;
```

Note the `DetailsElement` is defined in this file so you don't need to rely on `Vaadin.registrations`.

2021-02-08 16:51 UTC, web-padawan commented on test/details.test.js
> +      expect(toggle.getAttribute('aria-controls')).to.equal(`vaadin-details-content-${getUniqueId()}`);
Please consider using a RegEx here, same as in [vaadin-radio-group](https://github.com/vaadin/vaadin-radio-button/blob/ac80d5e6cac1b266c44da81bac79a1c13e930d15/test/radio-group.test.js#L541) tests.

2021-02-08 16:51 UTC, web-padawan commented on test/details.test.js
> +      expect(details[1]._collapsible.id).to.equal(`vaadin-details-content-${1 + id}`);
No need to check for specific number here. 
It is enough to compare the `id` of two elements and check they are different.

2021-03-22 12:12 UTC, closed without merging

2021-03-22 12:13 UTC, niiyeboah commented
Creating new PR for [web-components](https://github.com/vaadin/vaadin-web-components)